/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risk.shared;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
